version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    build: ./producer
    depends_on:
      - rabbitmq
  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq
